name: Deploy
on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
    - run: npm install
    - run: npm install -g vsce
    - name: Build Agent
      run: |
        cd agent
        npm install
        npm run build
    - name: Package VSIX
      run: vsce package
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ''
        draft: false
        prerelease: false
    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vscode-frida-${{ steps.version.outputs.VERSION }}.vsix
        asset_name: vscode-frida-${{ steps.version.outputs.VERSION }}.vsix
        asset_content_type: application/zip
